import { jsPDF } from 'jspdf';
import { callGemini } from '@/shared/services/gemini.service';
import { saveReport, linkCheckIns } from './reporte.service';
import type { AdminDashboardData } from '../hooks/useAdminDashboardData';

// ── Build the prompt ───────────────────────────────────────────────────────

function buildPrompt(data: AdminDashboardData, weekLabel: string): string {
  const totalOverdue = data.overdueByProject.reduce((s, r) => s + r.overdue, 0);
  const activeSprintCount = data.sprintHealth.reduce((s, r) => s + r.active, 0);

  // Keep per-project rows compact: top 10 only to save tokens
  const top = <T,>(arr: T[], n = 10) => arr.slice(0, n);

  const completionLines = top(data.completionByProject)
    .map(r => `${r.name}: ${r.rate}% (${r.done}/${r.total})`)
    .join(', ');

  const overdueLines = data.overdueByProject.length === 0
    ? 'none'
    : top(data.overdueByProject).map(r => `${r.name}: ${r.overdue}`).join(', ');

  const sprintLines = top(data.sprintHealth)
    .map(r => `${r.name}: ${r.active} active/${r.terminal} done`)
    .join(', ');

  const weeklyByProject = data.weeklyProgress.byProject.length === 0
    ? 'no items due'
    : top(data.weeklyProgress.byProject).map(r => `${r.name}: ${r.rate}%`).join(', ');

  return `Weekly project health report for ${weekLabel}. Write it as a professional report for leadership with these sections (plain text, no markdown #):
1. Executive Summary
2. Key KPIs
3. Project Health (one line per project)
4. Risks & Blockers
5. Recommendations

DATA:
- Active projects: ${data.activeProjects}, Total items: ${data.totalItems}, Active sprints: ${activeSprintCount}, Overdue: ${totalOverdue}
- Weekly completion: ${data.weeklyProgress.rate}% (${data.weeklyProgress.completed}/${data.weeklyProgress.total}) | By project: ${weeklyByProject}
- Completion rates: ${completionLines}
- Overdue by project: ${overdueLines}
- Sprint health: ${sprintLines}

Be concise. Each section max 4 sentences or bullet points.`;
}

// ── Build PDF ──────────────────────────────────────────────────────────────

function buildPdf(reportText: string, weekLabel: string): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
  };

  const checkY = (needed: number) => {
    if (y + needed > pageH - margin) addPage();
  };

  // ── Header bar ──────────────────────────────────────────────────────────
  doc.setFillColor(10, 8, 56); // --color-blueprint-navy
  doc.rect(0, 0, pageW, 64, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('JIXOLOGY', margin, 34);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(180, 190, 220);
  doc.text('Weekly Project Health Report', margin, 50);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(weekLabel, pageW - margin, 50, { align: 'right' });

  y = 64 + 28;

  // ── Body text ────────────────────────────────────────────────────────────
  const lines = reportText.split('\n');

  for (const rawLine of lines) {
    const line = rawLine.trim();

    // Detect section headers (e.g. "1. Executive Summary")
    const isHeader = /^\d+\.\s/.test(line) && line.length < 60;

    if (isHeader) {
      checkY(26);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(10, 8, 56);
      doc.text(line, margin, y);
      y += 16;

      // Underline
      doc.setDrawColor(10, 8, 56);
      doc.setLineWidth(0.5);
      doc.line(margin, y - 3, margin + contentW, y - 3);
      y += 6;
      continue;
    }

    if (line === '') {
      y += 6;
      continue;
    }

    // Bullet lines
    const isBullet = line.startsWith('-') || line.startsWith('•');
    const indent = isBullet ? margin + 12 : margin;
    const textWidth = isBullet ? contentW - 12 : contentW;

    doc.setFont('helvetica', isBullet ? 'normal' : 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(40, 40, 60);

    const wrapped = doc.splitTextToSize(
      isBullet ? `• ${line.replace(/^[-•]\s*/, '')}` : line,
      textWidth,
    );

    checkY(wrapped.length * 13 + 4);
    doc.text(wrapped, indent, y);
    y += wrapped.length * 13 + 3;
  }

  // ── Footer on every page ─────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 180);
    doc.text(
      `Page ${p} of ${totalPages}  •  Generated by Jixology  •  ${new Date().toLocaleDateString()}`,
      pageW / 2,
      pageH - 24,
      { align: 'center' },
    );
  }

  return doc;
}

// ── Public entry point ─────────────────────────────────────────────────────

export async function generateAndDownloadWeeklyReport(
  data: AdminDashboardData,
  userId: number,
): Promise<void> {
  const now = new Date();
  const day = now.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  const monday = new Date(now);
  monday.setDate(now.getDate() + diff);
  const friday = new Date(monday);
  friday.setDate(monday.getDate() + 4);

  const fmt = (d: Date) =>
    d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const weekLabel = `${fmt(monday)} – ${fmt(friday)}`;

  const reportText = await callGemini(buildPrompt(data, weekLabel));

  const reportId = await saveReport(reportText, monday, userId);
  await linkCheckIns(reportId, monday);

  const pdf = buildPdf(reportText, weekLabel);
  const filename = `weekly-report-${monday.toISOString().slice(0, 10)}.pdf`;
  pdf.save(filename);
}
