ALTER TABLE "usuario_grafica_visibilidad"
  ADD COLUMN IF NOT EXISTS "grid_x" SMALLINT,
  ADD COLUMN IF NOT EXISTS "grid_y" SMALLINT,
  ADD COLUMN IF NOT EXISTS "grid_w" SMALLINT,
  ADD COLUMN IF NOT EXISTS "grid_h" SMALLINT;
